# -*- coding: utf-8 -*-
"""과제_데이터분석과시각화.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fTdR4NkR05keWXx_74QWldBCMC98duXm

# 과목명 : 데이터분석과 시각화

## 과제설명

1. 아래 내용을 읽고 각 문제를 해결하는 코드를 완성하여 PDF로 제출하시기 바랍니다.
2. PDF가 아닌 노트북 파일 또는 Colab을 공유하여 제출하는 경우 감점이 됩니다.
3. 코드 이외 설명하는 내용 등 코드와 관계없는  내용이 포함되어도 관계없습니다.

## 과제제출

- 15주차 기말고사 일자이전에 제출

<hr>

## 문제상황

### 데이타 사전 지식

YouTube(세계적으로 유명한 동영상 공유 웹사이트)는 플랫폼에서 가장 인기 있는 동영상 목록을 관리합니다. 

버라이어티 매거진에 따르면 올해의 최고 인기 동영상을 결정하기 위해 YouTube는 사용자 상호 작용(조회 수, 공유 수, 댓글 및 좋아요 수)을 측정하는 등 여러 요인을 조합하여 사용합니다. 해당 연도 전체에서 가장 많이 본 동영상은 아닙니다.

YouTube 트렌딩 목록의 최고 성능은 뮤직 비디오(유명하게 남성적인 "Gangam Style" 등), 유명인 및/또는 리얼리티 TV 공연, YouTube에서 잘 알려진 무작위 카메라 바이럴 동영상입니다.

분석대상 데이터 셋은 인기 급상승 YouTube 동영상의 일일 기록입니다.

### 분석대상 데이터셋

- 분석 대상 데이터셋 : https://www.kaggle.com/datasets/datasnaek/youtube-new?select=KRvideos.csv
- 학습 공유 구글 드라이브에도 있습니다
- 파일명 : KRvideos.csv

### 과제 목표

- 분석 대상 데이터셋을 불러와 기술 통계정보를 확인합니다.
- 결측치를 확인하고 0 으로 치환 처리합니다.
- 중복된 데이터가 있다면 데이터 건수를 확인하고 삭제합니다.
- 채널별 조회수 합계를 구하고 시각화합니다.
- 채널별 조회수 합계를 구하고 상위 100건에 대해 시각화합니다.
- 'title','views'만 선택하여 많은 views 순으로 정렬 후 중복을 제거합니다.
- 'title' 컬럼 값을 이용하여 한글만 워드 클라우드 시각화를 합니다.
- 'views', 'likes', 'dislikes', 'comment_count' 컬럼 값의 상관계수 heatmap() 시각화를 합니다.
- 'category_id', 'views', 'likes', 'comment_count' 컬럼을 이용하여 유의미한 scatterplot(), barplot(), histplot(), countplot() 등 시각화를 합니다.
"""

import pandas as pd

KRvideo = pd.read_csv("KRvideos.csv")
KRvideo

KRvideo.info()

KRvideo.describe()

KRvideo.corr()